# Generated by Django 2.2.6 on 2019-10-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_prod',
            field=models.IntegerField(),
        ),
    ]
