# Generated by Django 2.2.5 on 2019-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=20)),
                ('date', models.DateField(help_text='Enter field documentation', max_length=20)),
                ('exchange_rate', models.FloatField(max_length=20)),
            ],
        ),
    ]
