# Generated by Django 2.2.6 on 2019-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=60)),
                ('currrency_code', models.CharField(choices=[('AUD', 'Австралійський долар'), ('CAD', 'Канадський долар'), ('CNY', 'Юань Женьмiньбi')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
