# Generated by Django 2.2.6 on 2019-10-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20191026_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencychoice',
            name='currency_name',
        ),
    ]
