# Generated by Django 2.2.6 on 2019-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_currencychoice_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencychoice',
            name='currency_rate',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
    ]
