# Generated by Django 2.2.5 on 2019-09-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190806_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='external_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExtQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=1000)),
                ('raw_data', models.CharField(max_length=1000)),
                ('received_date', models.DateTimeField(verbose_name='received date')),
                ('processed', models.BooleanField(verbose_name='processed date')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='processed date')),
                ('processed_error', models.TextField(blank=True, null=True, verbose_name='processed error')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Question')),
            ],
        ),
    ]
