# Generated by Django 2.2.5 on 2019-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190907_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extquestion',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed date'),
        ),
    ]
